### PR TITLE
[WIP] Limelight wrapper

### PR DESCRIPTION
**Pull request by AlexDvorak**
TODO:
- [x] add javadocs

### CODE REVIEW

**Comment by AlexDvorak** [comment]
Is there a better way to handle the `getValue` method than the `TableValue` enum? or perhaps a better way to write that enum/a completely different route alltogether? @matt-mekha

**Comment by matt-mekha** [comment]
yeah i think i can come up with a way

**Comment by AlexDvorak** [comment]
Do we need the `@CheckForNull` annotation on the `getValue` method?

**Comment by matt-mekha** [comment]
yeah sure @AlexDvorak

**Comment by AlexDvorak** [comment]
@matt-mekha what do you think?

**Comment by matt-mekha** [comment]
@AlexDvorak  looks good, we should start using Optional more often

**Comment by matt-mekha** [comment]
@DGKSK8LIFE i don't think that's worth the effort. You lose the autocomplete and the cohesiveness with the actual code. Also in some cases, the enums have java code as arguments in their constructors, which would be weird to translate into markdown.

**Comment by DGKSK8LIFE** [comment]
> @DGKSK8LIFE i don't think that's worth the effort. You lose the autocomplete and the cohesiveness with the actual code. Also in some cases, the enums have java code as arguments in their constructors, which would be weird to translate into markdown.
@matt-mekha 
It doesn't entail that much effort. The main advantage with that kind of configuration is that you don't have to go in and change much code. It's optimal for people who aren't as adept at programming. Also you wouldn't be using markdown for configuration LUL. And yeah, maybe sometimes there are places that require idiomatic java features; but for the places where it doesn't, we could implement json or yaml files for configuration pretty easily.

**Comment by AlexDvorak** [comment]
> The main advantage with that kind of configuration is that you don't have to go in and change much code. It's optimal for people who aren't as adept at programming.

Ideally, we don't need any configuration, because we test and see which parts work and which parts we like and don't like, and by competition we have the exact set of features we need and nothing more, and all the parameters are tuned and there is nothing to "configure" because it's already set in stone, and easy to change as it is. And, everyone should have at least a basic knowledge of the code, or there will be someone there with more experience (aka programming mentor) who can help change whatever parameters need to be changed. Or in the worst case, we contact a student with more experience who can walk the person through changing whatever needs to be changed, though, this rarely happens. @DGKSK8LIFE

**Comment by DGKSK8LIFE** [comment]
@AlexDvorak There are instances where bot drivers are accustomed to/are highly skilled with certain controller bindings or sensitivities. I think that bot operators should at least have the option to configure controls and such to their liking to optimize/facilitate their performance. The reason why I like configuration files is that they're pretty high-level and there are always times where there's no proxy or mentor/competent person to help out (for example mentors could be helping with repairs, etc). I think configuration files are nice because they're also portable (we don't have to fiddle about with version control and make a branch for each person; can just introduce different config files and call it a day). And there are still robotics team members who don't know how to program so I think it's fallacious to make the assumption that everyone knows what they're doing.

**Comment by AlexDvorak** [comment]
And I disagree, i think those situations are very few and far between, to the point where it's simply not worth the extra effort for the almost insignificant gain. Also, there should only be one driver throughout the season. Right, not everyone on the FRC team knows how to program, that's okay, and my point was that there is almost always someone who knows the code who is around to help out. Anyways, i'll add docs tomorrow and we'll go from there.

**Comment by DGKSK8LIFE** [comment]
> And I disagree, i think those situations are very few and far between, to the point where it's simply not worth the extra effort for the almost insignificant gain. Also, there should only be one driver throughout the season. Right, not everyone on the FRC team knows how to program, that's okay, and my point was that there is almost always someone who knows the code who is around to help out. Anyways, i'll add docs tomorrow and we'll go from there.

Configuration is an anomaly? It's probably like <= 10 lines of code to parse yaml objects (I think that java's OO structure might actually lengthen it though). Sure. There should be 1 driver, that's not always the case. Ok we'll go from there. Good talk!

**Comment by AlexDvorak** [comment]
Sorry, that got off track yesterday, to answer your original question:
> Could we possibly use json/yaml objects for some of our configuration/value settings instead of enums?

The reason we use enums is because the values in the enum `TableEntries` are constant, they are never gonna change, and so we would be creating extra work and making it more obscure and difficult to read and understand. All the values of this enum are constant, and pulled from [Limelight's documentation](https://docs.limelightvision.io/en/latest/networktables_api.html), so these aren't changing, hence there is nothing to "configure" per se.
```java
public enum TableEntry {
    hasValidTargets("tv"),
    targetXOffset("tx"),
    targetYOffset("ty"),
    targetArea("ta"),
    targetSkew("ts"),
    pipelineLatency("tl"),
    currentPipeline("getpipe", "pipeline"),
    operationMode("camMode", "camMode"),
    ledMode("LEDMode", "LEDMode");
    // ....
}
```

**Comment by DGKSK8LIFE** [comment]
@AlexDvorak technically json/yaml is immutable as well (at least programmatically). Why do you say that json/yaml is `more obscure and difficult to read and understand`. I guess I understand the point here, but in the future there will be things like controller binds (which IIRC you guys set with java instances) and offsets which will vary based on the user. Also for some things that may be less immediate (like auton PID calibration/auton behavior/procedures), a configuration system would be nice as it allows us to tweak settings/values on the fly.

**Comment by AlexDvorak** [comment]
@DGKSK8LIFE missing the point though, the enum isn't meant to be changed super often, and is relatively easy to change if necessary. I meant that the code for parsing yaml/json makes the codebase overall harder to understand. Also, we should almost never be changing values on the fly, you're treating the symptom of the problem, not the problem. The problem being that code was not completed on time, and said tuning should've been done before. Not to mention there are better ways than yaml/json to do this, such as SmartDashboard, which [was used last year for our shooter while tuning](https://github.com/awtybots/FRC-2020/blob/master/src/main/java/frc/robot/subsystems/ShooterSubsystem.java#L66)

**Comment by DGKSK8LIFE** [comment]
> @DGKSK8LIFE missing the point though, the enum isn't meant to be changed super often, and is relatively easy to change if necessary. I meant that the code for parsing yaml/json makes the codebase overall harder to understand. Also, we should almost never be changing values on the fly, you're treating the symptom of the problem, not the problem. The problem being that code was not completed on time, and said tuning should've been done before. Not to mention there are better ways than yaml/json to do this, such as SmartDashboard, which [was used last year for our shooter while tuning](https://github.com/awtybots/FRC-2020/blob/master/src/main/java/frc/robot/subsystems/ShooterSubsystem.java#L66)

@AlexDvorak How does it make the codebase harder to understand? Also, the whole point of `configuration` is to CHANGE VALUES ON THE FLY. Some people have different preferences for controlling the bot than others. It's a nice feature to have even if we don't use it most of the time. Also, why/how is `SmartDashboard` superior?

**Pull request merged**
